### ISSUE TITLE
use relative paths for file access

### ISSUE THREAD

**Issue by mbod** [Ankit-Saxena-7/communication-in-films#1]
In your RMarkdown and R code on the repo you should use relative file paths, e.g. 

```
tabMovieTitles <- read.csv(file="/Users/ankitsaxena/COMM-783/communication-in-films/Data/MovieTitles.csv", header=FALSE, sep="|")
```

drop the abs path to your home dir and folders and just have `Data/MovieTitles.csv`

**Comment by Ankit-Saxena-7** [comment]
Done!
